name: 'nomba_analytics'
version: '1.0.0'

profile: 'nomba_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  nomba_analytics:
    staging:
      +materialized: view

# Configuring seeds
seeds:
  nomba_analytics:
    stg_mongo_user:
      file: seeds/stg_mongo_user.csv
      header: true

